### ISSUE TITLE
explore log transforming right-skewed columns

### ISSUE THREAD

**Issue by a-arad** [project-palooza/unsupervised#2]
re-run preprocessing of the data but log transform right-skewed columns prior to scaling and winsorization.

**Comment by Sofia0204** [comment]
I can do this one c:

**Comment by a-arad** [comment]
do your best to write modular code -- make a function that accepts a data frame as its argument, checks for right skewed columns, then log transforms them, returning the transformed data frame. in addition, the function can print some kind of report -- maybe side by side histograms of pre-transform and post-transform for each effected column.

**Comment by a-arad** [comment]
hey I merged your pull request - great job!

I ended up removing the cell in the notebook where you print a table/plot report. It felt a bit disjointed from the rest of the notebook.

but I tested importing your module into the notebook, and it works!
