### ISSUE TITLE
clustering dashboard

### ISSUE THREAD

**Issue by a-arad** [project-palooza/unsupervised#3]
make a dashboard showing data points color-coded by kmeans cluster label in 2 or 3 dimensions.

to map data to a 2 or 3 dimensions use t-SNE or PCA. both techniques are available in scikitlearn and well documented.

put other relevant information in the dashboard.

use a python native dashboarding solution, like plotly/dash.

**Comment by ang2887** [comment]
I'd like to try this issue, please.

**Comment by a-arad** [comment]
i've added your dashboard

**Comment by ang2887** [comment]
Thank you 😅
